import Anthropic from "@anthropic-ai/sdk";
import config from "../utils/config.js";
import logger from "../utils/logger.js";
import { readMarkdown, readJson } from "../utils/corpus.js";

let client = null;

function getClient() {
  if (!client && config.anthropic.apiKey && config.anthropic.apiKey !== "placeholder") {
    client = new Anthropic({ apiKey: config.anthropic.apiKey });
  }
  return client;
}

/**
 * Generate a radio show from assembled runtime context.
 *
 * @param {object} runtimeContext — assembled by context.js:
 *   { weather, schedule, preferences, history, now }
 * @returns {object} { ok, data: { showTitle, mood, reason, playlist, djScripts } }
 */
export async function generateShow(runtimeContext) {
  const claude = getClient();
  if (!claude) {
    logger.warn("Claude API not configured, returning demo show");
    return { ok: true, data: demoTrack(), mock: true };
  }

  const systemPrompt = readMarkdown("templates/system-prompt.md");
  const now = runtimeContext.now || new Date().toISOString();

  const userMessage = [
    `现在是 ${now}`,
    "",
    "## 用户情境数据",
    "```json",
    JSON.stringify(runtimeContext, null, 2),
    "```",
    "",
    "请根据以上情境数据，为当前时刻策划一期音乐节目。",
  ].join("\n");

  try {
    logger.info({ model: config.anthropic.model }, "Calling Claude...");

    const msg = await claude.messages.create({
      model: config.anthropic.model,
      max_tokens: 2048,
      temperature: 0.8,
      system: systemPrompt,
      messages: [{ role: "user", content: userMessage }],
    });

    const text = extractText(msg);
    const show = parseShowJson(text);

    if (!show) {
      logger.error({ text: text.substring(0, 300) }, "Failed to parse Claude response");
      return { ok: false, error: "Failed to parse show JSON", data: demoTrack() };
    }

    logger.info({ title: show.showTitle, tracks: show.playlist?.length }, "Show generated by Claude");
    return { ok: true, data: show };
  } catch (err) {
    logger.error({ error: err.message }, "Claude API call failed");
    return { ok: false, error: err.message, data: demoTrack() };
  }
}

// ── Response Parsing ──────────────────────────────────────────

function extractText(message) {
  const block = message.content.find((b) => b.type === "text");
  return block?.text || "";
}

function parseShowJson(text) {
  // Try raw parse first
  try { return JSON.parse(text); } catch { /* continue */ }

  // Try extracting from ```json code block
  const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) {
    try { return JSON.parse(fence[1].trim()); } catch { /* continue */ }
  }

  // Try finding a JSON object in the text
  const objMatch = text.match(/\{[\s\S]*\}/);
  if (objMatch) {
    try { return JSON.parse(objMatch[0]); } catch { /* continue */ }
  }

  return null;
}

// ── Chat ──────────────────────────────────────────────────────

/**
 * Chat with PixWave DJ.
 * Priority: DeepSeek → Claude → mock
 * @returns {{ ok, data: { reply: string, action?: string, playTrack?: { searchKeyword } } }}
 */
export async function chat(userMessage, history = [], context = {}) {
  // 1) Try DeepSeek
  const { deepseekDjChat } = await import("../connectors/deepseek.js");
  const dsResult = await deepseekDjChat(userMessage, history, context);
  if (dsResult) {
    logger.info({ reply: dsResult.reply?.substring(0, 50), action: dsResult.action, play: !!dsResult.playTrack }, "DeepSeek chat response");
    return { ok: true, data: dsResult };
  }

  // 2) Try Claude
  const claude = getClient();
  if (claude) {
    try {
      const systemPrompt = readMarkdown("templates/chat-prompt.md");
      const messages = [...history.slice(-10), { role: "user", content: userMessage }];
      const msg = await claude.messages.create({
        model: config.anthropic.model, max_tokens: 512, temperature: 0.9,
        system: systemPrompt, messages,
      });
      const text = extractText(msg);
      const parsed = parseChatResponse(text);
      logger.info({ reply: parsed.reply?.substring(0, 50), action: parsed.action }, "Claude chat response");
      return { ok: true, data: parsed };
    } catch (err) {
      logger.error({ error: err.message }, "Claude chat API failed");
    }
  }

  // 3) Mock fallback
  return { ok: true, data: mockChatReply(userMessage, context), mock: true };
}

function parseChatResponse(text) {
  const replyMatch = text.match(/<reply>([\s\S]*?)<\/reply>/);
  const actionMatch = text.match(/<action>([\s\S]*?)<\/action>/);
  return {
    reply: replyMatch ? replyMatch[1].trim() : text.trim(),
    action: actionMatch ? actionMatch[1].trim() : null,
  };
}

function mockChatReply(message, context) {
  const msg = message.toLowerCase();
  let reply = "";
  let action = null;

  // Order matters: specific music genres before broad matches like "hi" (which matches "chill")

  // skip / next track
  if (msg.includes("跳过") || msg.includes("下一首") || msg.includes("切歌") || msg.includes("换一首") || msg.includes("不好听") || msg.includes("skip") || msg.includes("next") || msg === "换" || msg === "切") {
    reply = "收到，切到下一首！";
    action = "skip";
  } else if (msg.includes("换一批") || msg.includes("换节目") || msg.includes("再生") || msg.includes("重新") || msg.includes("再来")) {
    reply = "好的，我来重新选一批歌，稍等！";
    action = "regenerate";
  } else if (msg.includes("喜欢") || msg.includes("好听") || msg.includes("赞")) {
    reply = "太好了，你喜欢就好！我记下来了。";
    action = "like";
  } else if (msg.includes("什么歌") || msg.includes("在放") || msg.includes("current")) {
    const track = context.currentTrack;
    reply = track
      ? `现在在放的是 ${track.songName} — ${track.artist}，觉得怎么样？`
      : "目前没有在播放任何歌曲。要不生成一期节目试试？";
  // music genres (before broad short-word matches)
  } else if (msg.includes("爵士") || msg.includes("jazz")) {
    reply = "哦，爵士好品味！让我找找适合现在听的爵士曲目。";
    action = "search:jazz";
  } else if (msg.includes("摇滚") || msg.includes("rock")) {
    reply = "想嗨起来？没问题！我来安排几首带劲的。";
    action = "search:rock";
  } else if (msg.includes("放松") || msg.includes("chill") || msg.includes("安静") || msg.includes("轻音乐")) {
    reply = "懂了，放松模式开启。找几首舒缓的给你。";
    action = "search:chill";
  } else if (msg.includes("古典") || msg.includes("classical") || msg.includes("钢琴")) {
    reply = "古典音乐是个好选择，让我挑几首优雅的。";
    action = "search:classical";
  } else if (msg.includes("电子") || msg.includes("electronic") || msg.includes("edm")) {
    reply = "电子乐来了！准备好耳朵。";
    action = "search:electronic";
  } else if (msg.includes("中文") || msg.includes("华语") || msg.includes("国语")) {
    reply = "华语歌曲，没问题！我来选几首好听的。";
    action = "search:chinese";
  // greetings (after specific keywords to avoid false matches like "hi" in "chill")
  } else if (msg.includes("你好") || msg === "hi" || msg === "嗨" || msg.includes("hello")) {
    reply = `嗨！我是 PixWave，你的 AI 音乐 DJ。${context.showTitle ? `当前节目是「${context.showTitle}」。` : ""}有什么想听的风格，或者想聊聊音乐吗？`;
  } else {
    reply = `哈喽！我是 PixWave。${context.showTitle ? `现在在播「${context.showTitle}」。` : ""}想听什么风格？爵士、摇滚、电子、放松、古典、华语……或者直接说「换一首」也行！`;
  }

  return { reply, action };
}

// ── Demo / Fallback ───────────────────────────────────────────

function demoTrack() {
  return {
    showTitle: "午后微风",
    mood: "chill",
    reason: "午后的阳光正好，来点轻松的旋律",
    playlist: [
      {
        order: 1,
        songName: "夏日漱石",
        artist: "橘子海",
        reason: "慵懒的吉他 riff 适合这个温度",
        searchKeyword: "橘子海 夏日漱石",
      },
      {
        order: 2,
        songName: "Intro",
        artist: "The xx",
        reason: "极简的电子氛围承接午后的宁静",
        searchKeyword: "The xx Intro",
      },
      {
        order: 3,
        songName: "带我去找夜生活",
        artist: "告五人",
        reason: "节奏略微上扬，为下午注入活力",
        searchKeyword: "告五人 带我去找夜生活",
      },
    ],
    djScripts: [
      {
        beforeTrack: 1,
        text: "嗨，下午好。外面阳光不错，摄氏22度，挺舒服的。先来一首橘子海的《夏日漱石》，给这个午后开个头。",
      },
      {
        beforeTrack: 3,
        text: "刚才那首来自 The xx，极简又带点迷幻。接下来换换口味，告五人的歌，让你下午精神一点。",
      },
    ],
  };
}
